#!/bin/bash

set -ef -o pipefail

export JAVA_TOOL_OPTIONS="-javaagent:/opt/newrelic/newrelic.jar ${JAVA_TOOL_OPTIONS}"

########################################

ARGS=("$@")
EXTRA_ARGS=()

if [ -z "${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED}" ]; then
  export NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=false
  echo "Setting NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED to be false"
fi

if [ -z "${NEW_RELIC_CROSS_APPLICATION_TRACER_ENABLED}" ]; then
  export NEW_RELIC_CROSS_APPLICATION_TRACER_ENABLED=false
  echo "Setting NEW_RELIC_CROSS_APPLICATION_TRACER_ENABLED to be false"
fi

if [ -z "${NEW_RELIC_SPAN_EVENTS_COLLECT_SPAN_EVENTS}" ]; then
  export NEW_RELIC_SPAN_EVENTS_COLLECT_SPAN_EVENTS=true
  echo "Setting NEW_RELIC_SPAN_EVENTS_COLLECT_SPAN_EVENTS to be true"
fi

if [ -z "${NEW_RELIC_TRANSACTION_TRACER_COLLECT_TRACES}" ]; then
  export NEW_RELIC_TRANSACTION_TRACER_COLLECT_TRACES=true
  echo "Setting NEW_RELIC_TRANSACTION_TRACER_COLLECT_TRACES to be true"
fi

if [ -z "${NEW_RELIC_LOG_FILE_NAME}" ]; then
  export NEW_RELIC_LOG_FILE_NAME=stdout
  echo "Setting NEW_RELIC_LOG_FILE_NAME to be stdout"
fi

if [ -z "${NEW_RELIC_APP_NAME}" ]; then
  export NEW_RELIC_APP_NAME=lambda-function
  echo "Setting NEW_RELIC_APP_NAME to be lambda-function"
fi

if [ -z "${NEW_RELIC_SERVERLESS_MODE_ENABLED}" ]; then
  export NEW_RELIC_SERVERLESS_MODE_ENABLED=lambda-function
  echo "Setting NEW_RELIC_SERVERLESS_MODE_ENABLED to be true"
fi

if [ -z "${NEW_RELIC_CLASS_TRANSFORMER_AWS_LAMBDA_JAVA_CORE_ENABLED}" ]; then
  export NEW_RELIC_CLASS_TRANSFORMER_AWS_LAMBDA_JAVA_CORE_ENABLED=true
  echo "Setting NEW_RELIC_CLASS_TRANSFORMER_AWS_LAMBDA_JAVA_CORE_ENABLED to be true"
fi

export NEW_RELIC_LITE_MODE=true
echo "Always setting NEW_RELIC_LITE_MODE to be true"

export NEW_RELIC_ENABLE_AUTO_APP_NAMING=false
echo "Always setting NEW_RELIC_ENABLE_AUTO_APP_NAMING to be false"

ARGS=("${ARGS[0]}" "${EXTRA_ARGS[@]}" "${ARGS[@]:1}")

exec "${ARGS[@]}"
