#!/bin/bash

set -ef -o pipefail

source /opt/lib-handler.sh
ARGS=("$@")
EXTRA_ARGS=()

setup_agent $ARGS $EXTRA_ARGS

export NEW_RELIC_LITE_MODE=true
log_debug "Always setting NEW_RELIC_LITE_MODE to be true"

if [ -z "${NEW_RELIC_CLASS_TRANSFORMER_AWS_LAMBDA_JAVA_CORE_ENABLED}" ]; then
  export NEW_RELIC_CLASS_TRANSFORMER_AWS_LAMBDA_JAVA_CORE_ENABLED=true
  log_debug "Setting NEW_RELIC_CLASS_TRANSFORMER_AWS_LAMBDA_JAVA_CORE_ENABLED to be true"
fi

ARGS=("${ARGS[0]}" "${EXTRA_ARGS[@]}" "${ARGS[@]:1}")

exec "${ARGS[@]}"