name: Publish Node Layers

on:
  push:
    tags:
      - v**_nodejs

jobs:
  publish-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        id: setup
        uses: ./.github/actions/node-layer-setup
        with:
          node-version: ${{ matrix.node-version }}
      - name: Publish layer
        if: steps.setup.outputs.tag-match == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make publish-nodejs${{ matrix.node-version }}-ci
      - name: Publish ECR image for nodejs${{ matrix.node-version }}
        if: steps.setup.outputs.tag-match == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd nodejs
          ./publish-layers.sh build-publish-${{ matrix.node-version }}-ecr-image
      - name: Upload Unit Test Coverage
        if: steps.setup.outputs.tag-match == 'true'
        uses: codecov/codecov-action@v5.3.1
        with:
         token: ${{ secrets.CODECOV_TOKEN }}
         files: ./nodejs/coverage/unit/lcov.info
         fail_ci_if_error: true
         flags: unit-tests

  publish-node-universal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        id: setup
        uses: ./.github/actions/node-layer-setup
        with:
          node-version: 22
      - name: Publish universal layer
        if: steps.setup.outputs.tag-match == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make publish-nodejs-universal-ci
      - name: Publish universal ECR image
        if: steps.setup.outputs.tag-match == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd nodejs
          ./publish-layers.sh build-publish-universal-ecr-image
      - name: Upload Unit Test Coverage
        if: steps.setup.outputs.tag-match == 'true'
        uses: codecov/codecov-action@v5.3.1
        with:
         token: ${{ secrets.CODECOV_TOKEN }}
         files: ./nodejs/coverage/unit/lcov.info
         fail_ci_if_error: true
         flags: unit-tests
