name: Publish Python Layers

on:
  push:
    tags:
      - v**_python

jobs:
  publish-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', '3.14' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        id: setup
        uses: ./.github/actions/python-layer-setup
      - name: Publish Python ${{ matrix.python-version }} layer
        if: steps.setup.outputs.tag-match == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd python
          ./publish-layers.sh python${{ matrix.python-version }}

  publish-python-universal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        id: setup
        uses: ./.github/actions/python-layer-setup
      - name: Publish universal Python layer
        if: steps.setup.outputs.tag-match == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd python
          ./publish-layers.sh python
